### ISSUE TITLE
Tests for library and proper "package" file structure.

### ISSUE THREAD

**Issue by Thavarshan** [PHPWatch/resource#3]
Would like to know if you intend to write tests for the library and would like all the files necessary for a PHP package like `.editorconfig` and `LICENSE`. Have submitted a PR (#2) if you do.

**Comment by Thavarshan** [comment]
Submitted another PR (#4) with cleanup done according to previous comments.

**Comment by Ayesh** [comment]
Thank you. #4 is merged with thanks. 
I made a few minor changes, basically enabling coverage reports on top your phpunit config. 

I will review/reply to the rest soon, but I think in a couple days because I will be 12-14 hours on the road tomorrow. 
Cheers.
