### ISSUE TITLE
Specification on which resource types to use for library

### ISSUE THREAD

**Issue by Thavarshan** [PHPWatch/resource#5]
The PHP website contains a huge list of PHP [resource types](https://www.php.net/manual/en/resource.php). I'd like to know if this library is going to create adapters for all or just a bunch of specific resources.

**Comment by Ayesh** [comment]
Thanks for the good question. 

The attempt is to help the transitional period of resources, so I think [extensions that affected](https://php.watch/articles/resource-object) will be supported for sure. 

There are some missing extensions such as enchant and and xmlrpc (moved to PECL in PHP 8.0) that will be supported as well, just that the article is not updated yet. 

For now, let's keep the extensions that are widely used (vague criterion I know), so please feel free to use your judgement.

**Comment by Thavarshan** [comment]
Ill do my best to sort them out but just to make sure, I'll ask before starting on one.
